basePath: /
definitions:
  controllers.PostRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  controllers.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  controllers.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://localhost:8080/
  description: This is a sample server celler server.
  termsOfService: http://localhost:8080/
  title: Onycom API
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: GetPosts
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 페이지 번호
        in: query
        name: page
        type: integer
      - description: 페이지 당 게시글 수
        in: query
        name: limits
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 게시글 목록
          schema:
            type: object
        "401":
          description: 인증되지 않은 사용자입니다.
          schema:
            type: string
      summary: GetPosts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: CreatePost
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 제목과 내용
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.PostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 게시글이 성공적으로 생성되었습니다.
          schema:
            type: string
        "400":
          description: 제목과 내용을 모두 입력해야 합니다.
          schema:
            type: string
        "401":
          description: 인증되지 않은 사용자입니다.
          schema:
            type: string
      summary: CreatePost
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: DeletePost
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 게시글 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 게시글이 성공적으로 삭제되었습니다.
          schema:
            type: string
        "400":
          description: 잘못된 게시글 ID입니다.
          schema:
            type: string
        "401":
          description: 인증되지 않은 사용자입니다.
          schema:
            type: string
        "403":
          description: 게시글 삭제 권한이 없습니다.
          schema:
            type: string
        "404":
          description: 게시글을 찾을 수 없습니다.
          schema:
            type: string
        "500":
          description: 게시글 삭제 중 오류가 발생했습니다.
          schema:
            type: string
      summary: DeletePost
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: UpdatePost
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 게시글 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 제목과 내용
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 게시글이 성공적으로 수정되었습니다.
          schema:
            type: string
        "400":
          description: 잘못된 입력 값입니다.
          schema:
            type: string
        "401":
          description: 인증되지 않은 사용자입니다.
          schema:
            type: string
        "403":
          description: 게시글 수정 권한이 없습니다.
          schema:
            type: string
        "404":
          description: 게시글을 찾을 수 없습니다.
          schema:
            type: string
        "500":
          description: 게시글 수정 중 오류가 발생했습니다.
          schema:
            type: string
      summary: UpdatePost
      tags:
      - posts
  /users/signin:
    post:
      consumes:
      - application/json
      description: SignIn
      parameters:
      - description: 이메일과 비밀번호
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 로그인에 성공했습니다.
          schema:
            type: string
        "401":
          description: 비밀번호가 올바르지 않습니다.
          schema:
            type: string
        "500":
          description: 리프레시 토큰 저장에 실패했습니다.
          schema:
            type: string
      summary: SignIn
      tags:
      - users
  /users/signup:
    post:
      consumes:
      - application/json
      description: SignUp
      parameters:
      - description: 이메일과 비밀번호
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 회원가입에 성공했습니다.
          schema:
            type: string
        "400":
          description: 비밀번호 암호화에 실패했습니다.
          schema:
            type: string
        "500":
          description: 회원가입에 실패했습니다.
          schema:
            type: string
      summary: SignUp
      tags:
      - users
schemes:
- http
swagger: "2.0"
